app/__init__.py
import os

from flask import Flask
from .config import Config
from app.errors.routes import error_401, error_403, error_404, error_500


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_ENV', 'development')

    app = Flask(__name__)
    app.config.from_object(Config)

    # Initialization of blueprits
    # I Blueprints in Flask sono uno strumento potente per organizzare, riutilizzare e
    # mantenere il codice delle applicazioni web in modo efficiente, rendendo più semplice la gestione di
    # applicazioni più complesse e scalabili

    from app.main import main_blueprits
    app.register_blueprint(main_blueprits)

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    return app

app/main/__init__.py
from flask import Blueprint

main_blueprits = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from torchvision import transforms
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField

from flask import render_template, Response, flash, jsonify
from app.main import main_blueprits
from app.source.utils import classify_image


# from source.test_new_images import detect_mask_in_image


@main_blueprits.route("/")
def home_page():
    return render_template("home_page.html")


def allowed_file(file):
    extention_file = file.split(".")[-1]
    return extention_file in ['jpg', 'jpeg', 'png']


@main_blueprits.route("/image-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_blueprits.route("/image_processing_old", methods=["POST"])
def image_processing_old():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)

    label, _ = classify_image(pil_image.convert('RGB'), transform)

    image_detected = Image.fromarray(image, 'RGB')
    # image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img, label


@main_blueprits.route("/image_processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)

    label, _ = classify_image(pil_image.convert('RGB'), transform)

    image_detected = Image.fromarray(image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')

    return jsonify({"image": base64img, "label": label})


class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Classification')
    cancel = SubmitField('Cancel')

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Automatic X-ray image detection of pneumonia and COVID-19</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div class="row">
            <div class="container">
                <h2>Obiettivo del Progetto</h2>
                <p>
                    L'obiettivo del presente progetto è lo sviluppo di un sistema avanzato basato su tecniche di apprendimento automatico e visione artificiale, finalizzato alla discriminazione diagnostica su immagini radiografiche (raggi X) per identificare lo stato di salute del soggetto. In particolare, il sistema è progettato per distinguere tra soggetti sani, affetti da polmonite o positivi al COVID-19.
                </p>

                <h3>Funzionamento del Sistema</h3>
                <p>
                    Il sistema si basa su una pipeline di elaborazione delle immagini strutturata in diverse fasi. La prima fase comprende l'acquisizione dell'immagine radiografica, seguita da un pre-processamento per migliorare la qualità e la leggibilità del dato. Successivamente, il sistema applica un algoritmo di classificazione basato su reti neurali profonde (Deep Learning), addestrato su un ampio dataset annotato per riconoscere con elevata precisione le diverse condizioni cliniche.
                </p>

                <h3>Applicazioni</h3>
                <p>
                    L'algoritmo proposto rappresenta un potenziale strumento di supporto diagnostico per i professionisti sanitari. Grazie alla sua capacità di analizzare rapidamente immagini radiografiche, il sistema può essere impiegato come fase iniziale di valutazione clinica, offrendo un'indicazione preliminare utile al medico per orientare decisioni successive o priorizzare i casi più critici.
                </p>

                <h3>Architettura del Sistema</h3>
                <p>
                    L'architettura del sistema è basata su una rete neurale convoluzionale (Convolutional Neural Network, CNN), progettata e ottimizzata per l'analisi delle immagini radiografiche. Il modello è stato addestrato su un ampio dataset costituito da immagini radiografiche di soggetti sani e pazienti affetti da polmonite o COVID-19 (<a href="https://www.kaggle.com/datasets/prashant268/chest-xray-covid19-pneumonia/data" target="_blank">visulizza dataset</a>), garantendo robustezza e accuratezza nelle predizioni. Per ulteriori dettagli sull'implementazione e sui dataset utilizzati, si rimanda alla documentazione tecnica disponibile sul repository GitHub di riferimento.
                </p>
            </div>

        </div>
        <hr>
    </div>
</div>
{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Welcome to Image Classification</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">

        <div class="row">
            <h4>Come funziona?</h4>
        </div>
        <div class="row">
            <p>
                L'utente può caricare un'immagine statica tramite l'interfaccia dedicata. Successivamente, l'algoritmo esegue un'analisi automatica dell'immagine e ne fornisce la classificazione.
            </p>
        </div>

        <hr>
        <div id="frame_container" class="row">
             <div class="col-12">
                <img src="" id="image-preview" style="max-width:600px; display: none !important;"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div id="result-container" class="row mt-3">
            <div class="col-12 d-flex justify-content-center">
                <h4 id="detection-result">Carica File</h4>
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary mx-2", id="submit", disabled=True) }}
                            {{ form.cancel(class="btn btn-danger mx-2", id="cancel", disabled=True) }}
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled", false);

    $("#cancel").prop("disabled", false);
    // $("#form-row").remove();
    $("#form-row").css("display", "none");
    $("#detection-result").text("Immagine caricata!");

};

$(document).ready(function() {
    $('#live').attr('class', 'nav-item');
    $('#image-detector').attr('class', 'nav-item active');
});

$(function() {
    $("#cancel").each(function (index) {
        $(this).on('click', function (e) {
           e.preventDefault();
           location.reload(); // reload the current page
        });

    });

    $("#submit").each(function(index) {
        $(this).on('click', function(e) {
            e.preventDefault();

            var url = "{{ url_for('main.image_processing') }}";

            // Creazione del formData
            var formData = new FormData();

            // Aggiungi dati del form
            $('#image-form').serializeArray().forEach(function(item, index) {
                formData.append(item.name, item.value);
            });

            // Aggiungi file immagine
            var image = $('#new-image')[0].files[0];
            formData.append('image', image);

            // Richiesta AJAX al server
            $.ajax({
                type: "POST",
                url: url,
                data: formData,
                processData: false,
                contentType: false,
                success: function(response) {
                    // Aggiorna l'immagine e la classe
                    $("#image-preview").attr("src", response.image);

                    $("#detection-result").text("Risultato: " + response.label);

                    // Cambia il pulsante di invio
                    $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                    $("#form-row").remove();

                    $("#cancel").remove();
                },
                error: function(response) {
                    alert("Errore durante l'elaborazione dell'immagine.");
                    location.reload();
                }
            });

            return false;
        });
    });
});
</script>
{% endblock %}

app/templates/index.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Welcome to the mask detector live</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/live_mask_detection.png" id="video-feed" class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera" aria-hidden="true"></i> Start</button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop" aria-hidden="true"></i> Stop</button>
            </div>
        </div>
        <hr>
        <div class="row">
            <h4>What is this?</h4>
        </div>
        <div class="row">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people through your camera and writes a bounding box around faces, determining if they are wearing masks or not.</p>
            <p>Try it!</p>
        </div>
        <div class="row">
            <h4>Who I am</h4>
        </div>
        <div class="row mb-5">
            <p>Descrizione:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>Please, stay safe and wear a mask</strong>.</p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
$(document).ready(function(){
    $('#image-detector').attr('class', 'nav-item');
    $('#live').attr('class', 'nav-item active');
})

function stop(){
    $("#video-feed").attr("src", "/static/images/live_mask_detection.png");
    $("#stop").attr("class","btn btn-danger active");
    $("#start").attr("class","btn btn-outline-success");
}

function start(){
    $("#video-feed").attr("src", "{{ url_for('video_feed') }}");
    $("#start").attr("class","btn btn-success active");
    $("#stop").attr("class","btn btn-outline-danger");
}
</script>
{% endblock %}

app/templates/template.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>Automatic X-ray detection</title>
    <style>
        .footer-link{ color: inherit; }
        .footer-link:hover{ color: inherit; }
        body {
    margin: 0;
}

.wrapper {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}

.footer {
    margin-top: auto;
}
    </style>
</head>
<body>
<div class="wrapper">
    <div class="header">
        <!--navbar start-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/"><i style="font-size:24px" class="fa">&#xf015;</i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item" id="image-detector">
                        <a class="nav-link" href="/image-detector">Image Classification</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!--navbar end-->
    </div>
    <div class="content">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}

        <!--add custom content with inheritance-->
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="py-4 bg-dark text-white-50">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <p>All my links:</p>
                        <div class="row">
                            <div class="col-4">
                                <a href="https://www.linkedin.com/in/lorenzo-de-feo-717728203/" class="footer-link">
                                    <i class="fa fa-linkedin-square my-auto mx-2" aria-hidden="true"></i> Linkedin
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="https://github.com/lorenzodefeo" class="footer-link">
                                    <i class="fa fa-github mx-2 my-auto" aria-hidden="true"></i>GitHub
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="mailto:lorenzodefeo2@gmail.com?subject=Automatic X-ray image detection of pneumonia and COVID-19" class="footer-link">
                                    <i class="fa fa-envelope my-auto mx-2" aria-hidden="true"></i> Mail
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- jQuery, Popper.js, and Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>